monorepo_root = true

[settings]
experimental = true
env_shell_expand = true

[monorepo]
config_roots = ["apps/*", "userscript"]

[tools]
# languages
bun = "1.3"
node = "24"

# tools
just = "latest"
prek = "latest"
process-compose = "latest"
"npm:get-port-cli" = "latest"
