apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: image-proxy-config
stringData:
    Caddyfile: ENC[AES256_GCM,data:X23q/q9FTnnbcdlaMVoQvdrfIQsGfkWTXP/JKGg3F/dhax1Xe/IslAq58gykoZf6c2SvN4OCrHxepi6PalXsjJySUCsStgNpxRXw3+a1wA+rpPf0dV4Og9otmJgIKc+1TfMGnHQk/0TJsp9kE5B4Ce4/hoq4X/uKGBuvHw7zIKLCe+0itYCUxxYdb+LMo+oOJx6Z9sivR0QGPD4sael0JRWFW9K5sUIFJQPCyo2hiab4iv/g/ThmP1XP5qP/W1aFqr4UZRPCLqKlbbVNNe2+eOf0jZ5yUWtx0+u3QhBWohoHgx7ZbOSXht6NmR/Rl7pSAcMln3WQKxf9f2+aBlb/O0W2bk9+QaIfoe8b/njmKuo3x/gZ7BpYs8BEmTm8u7FMCJUMmPnhy0wSn3j1ZgZFZhKG3JlO5X64uRTbOPxhdzY0S2lqqAAXouNO8fUawOdV1S8qTajlGyICLQ9qSri5DcUmInX5nVySYtMbu92IDBZvKvqRkApczcAUH1/sJm8xLtuhb2h9y6ny4KSfFbSW77moMz3waSO6dMDe0ptuaKd/QPerT95qL1SjN/4dEEKO1RyD6WAGqSdX1i2Lm56Vlikb6mn+amaqR2Lq5oxw19gXzvZK0aM/dB3VwKOCt/gCgNCaFwJHo1yXXKkME5T+X9ANQzvB5pIEs6cyc7j5Cqlguv4up4XOa8jTUElSQZc=,iv:11mRZFsZQGEFluk+Eq6QnzGmniH3WUNaK9ormFBaVWc=,tag:ziWzZo36g70gJ4aOvWNafg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaEdEeDF0Z0VPcFVQSlFB
            VXdoL1ByU2M3TDdLbEFvaWI2OVhOUitZbVUwCklzVUlXTDc2SmhHL0hHOXpNZkhv
            c2hjV00rQXZudGRwZE5walJLYXh0S2sKLS0tIER6TERXaVc5VXE1aWdmeHBzL21t
            NE81ZXpRd0pkMVVDWEs3Z3NHUHV4dGcKQ2ZXcUux55FVEFvvathFUXvOpnWZXdx/
            NJU4OTsT3hxbyXWbhJpstbxdRxIkJlDRDrl6Ao5VwUPdDpVf2hhzwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nmyhrpnparuwdkny03zxc52gn488qumxw865ss3vavkqxvauhfwq0e7y34
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T18:37:24Z"
    mac: ENC[AES256_GCM,data:skjw4Qsd5BBi7bsF3F7TAmLvhKYLlVl3YhBPYI78cb0N/8WSOWBBBoqbH0TNuazaZxqcupMkfCQVS3LviwlIt1IlOZIJNJpGi/uCXriIrXqHxkw+qI3PHG8nvScOHUJFGYf8QaylIhQZ7i4fNMDW1BNVaP5vNrvf9Q2rY3Unzd4=,iv:sUzQG190/FhK7qH30GtytOhzjRdgVKgGjVxQwYuWrzU=,tag:YCda3r9gm6WSdOnWFdA0Lw==,type:str]
    version: 3.13.2
