apiVersion: v1
kind: Secret
metadata:
    name: registries
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:xDnkyT7BPN0Jf59du9EMnWGaLRnr2sE2v9hDCwY9IYxFErrMP2mPv4smVUaNfoTfZgLa7fuI0zarh1UIQ1jI84nsotqvFQYpYC4vs58Ij1bYrUWtUktzbSjGBu9oFfMKbrGlLmvjmfQ8EPsPkeNQKplyf7ICmZOPejZqc+mP3A8vEznidfmysejowRigXPN/kyi8b7UvtcJI5tdTkOPWvB1Sy7a4SGwpAbBg3f9yxIIUBdhVGtiWPk0e6uMTgMgNy0dCB/GImKLM1FlMVclpgqgv74wKjyw=,iv:gy8bb8ClwRNe1+EPg+0B2H4zSkmGb0LZzBJb4RXP81E=,tag:nIthY5t5GYYw0X/XRsyjJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNHlIdzVZdkhqWnZvT2pl
            dTJ1OWdtejJoMElacXJrc1RBK2ZJNzMyK3hnCkc1ZkV0T3RPQ2RrRW5DR0dvNnZt
            RUxrWjlGS2lYOGd4U1VlRFRUYmd0ejAKLS0tIHJOZC94YllVVS9Pb2dlUTZibEd6
            SXI5NEZ0V1JlS0REbjMxckIvSFdsMkkKR9gNCVdP1XDuzPUhI2vFrRj/bgNPSO/O
            fo1FOhwGJdH2mX2xPzxKk6wRc+vxVmRM7mlvtMRKLU63K2QKww12yA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nmyhrpnparuwdkny03zxc52gn488qumxw865ss3vavkqxvauhfwq0e7y34
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T19:59:47Z"
    mac: ENC[AES256_GCM,data:wTVAWAbO56n3sxOwYi5DOEnPK8LiGlQgIil8BQWXj8rZslEEy6mAlhIpotYijeKn01QsgwFL+B+gA3TTf6RTbDdFrBkhwVk6kOYYpKjQN4ch6YCkzwsK7bbbryEUvqAbxu357YxK/nyA+uoVuOrL2hdE0SRMWvhQXThSOajSCNA=,iv:GEMGD7nqHZZSCf3WGoupUZxYD3AJsoNRo/3JWjmTPA0=,tag:l4OSmSN1j6C0Sn82ab1w+g==,type:str]
    version: 3.13.2
