apiVersion: v1
kind: Secret
metadata:
    name: docs-update-webhook-token
stringData:
    token: ENC[AES256_GCM,data:ntgZyvuUTK0YCBprPvabvfxzb02qD1+Uwv5ruIAX5osR6Igt4kOWm6VEWRkbeBhD9k/xpEoSvLcxTF5Vd61w9g==,iv:l4M3Zt8drqMANrJdnqY1vayJmlQA0F5K4xQnQZBItzo=,tag:kaqOuHnn4uCtUZ5WTdVswA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoN2hRclVoRXdBRmVBS1BH
            SEMva1BiREZWR3EyWjl4OURUUkQwbDg2eFdBCi94RlVkaDBIQytoVXpkdEszQnZL
            Tmd0ZUsyTFlKcGtVQkR2dC9Yc0UzM0UKLS0tIEYyMEloM3p4YytJSzNpaVRxMmRB
            MG11cEJ2b1RmL01TUHBUUG9PNmJjYjgKrfIrEJxNFzuHYrpvtGSOO8a/anjCnuvg
            mX9ZocAeR7G0dRpOid+r7yc5f9RYX70tMYifjb1rCbMuq5GhfZAEAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nmyhrpnparuwdkny03zxc52gn488qumxw865ss3vavkqxvauhfwq0e7y34
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T22:07:21Z"
    mac: ENC[AES256_GCM,data:z28ixr06Jr0IeVnNYUObb0bjAAZBkrrY2+0NDluiMxCiAiMT6tPD/LHltoTImDat/Ke1lgV7UC2KC0ob3h+ZNiFPBkKGTl7Hs+QdmEUbiHeSoLk2AFPFqrS/qGlGVAcGqDGVuMxk1+L7CUHxk2062q9teeS/ihfSh1CnonZEw2I=,iv:vhCpo7j8jokbir+FPp/rAni8TCszzLtN1I3EVuGRR+w=,tag:nIX1rktyt7gxe9nmM9ZzJg==,type:str]
    version: 3.13.3
