apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: discord-bot-config
    files:
      - config.yaml
resources:
  - deployment.yaml
  - cronjob.yaml
  - model-cache.yaml
  - secrets.enc.yaml
  - image-update.yaml
  - sa.yaml
  - network-policy.yaml
