apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: discord-bot-egress-restricted
spec:
  endpointSelector:
    matchLabels:
      app: discord-bot
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
          rules:
            dns:
              - matchPattern: "*"
    - toServices:
        - k8sService:
            serviceName: api
            namespace: geometa
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: geometa
            app: api
      toPorts:
        - ports:
            - port: "3000"
              protocol: TCP
    - toFQDNs:
        - matchName: gateway.discord.gg
        - matchName: discord.com
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
