apiVersion: v1
kind: Secret
metadata:
    name: discord-bot
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:byu+igjrvAKWHShVkDfAU7pC9ZHxzCpbC6N6DJ99FYE623B1UuP9h33UY6UoqxF9X8vSihMRZSQFmpcZU+o78AoGN3tChVea,iv:ulgew2y1aqH/Gbg/vc2y5/IL3AeCcHeCGc+Xp+xp0OY=,tag:uSTjb5YiXSOJtM2Za+w+1A==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:gytEewgVxUI8PXvHaO34JGT1mPXDJV4HX56RJHUY/LpQhP3vFJ2+vTgJZDJ2cTU+mqdhry9hVGoP4fWwpu+1hKoORK1K8NI00A==,iv:JgSw4itTmBGJJhyodNpLmFGjPIsWSCv9QPPBn/BB6N8=,tag:97A8lvA7Fl62U0TUabhPTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UG54VHMrUVErT2xtbDhL
            REpQUjA1L0Y3NUxMUGkra3FsUU8vT01zTVhnClBpNUZnbTZHT0JsNjdsQk1hdkV1
            dVpsVFR0K2tFUHB0enEvL0ZMN2tVWnMKLS0tIDNjL1U4Q2FMM0tVdUYvcWFsOS9M
            RFFmMmZablMwVlRIZlBnZjRqT2J4YzAKoI74oaggQaYm5ut79PZuWwU6qjxSN/Ku
            qoeS3BxEeuVouzLKDIQ4pkABsjVqnJO58A1FTO5gbucrZqNhhCsz0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nmyhrpnparuwdkny03zxc52gn488qumxw865ss3vavkqxvauhfwq0e7y34
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T21:23:24Z"
    mac: ENC[AES256_GCM,data:P06bjQlBG/xgGGqwQpplGc3qlZORUtx4xe1XAMmBecf8Xxb2zzvjAfA0G/pqQjf64/2Q5jM+Qoi3B5GlX2Z3rDG7wBi2tGzWj3yxZMf+YMkRrH+ifoOMFzbRBhosq+aphaBDXdAXowiVQGr2xkPOcig6X37U19q4gVU+LCi9uGs=,iv:7cfrUeD78VuMtbvUDsbtmGytuYdHtRsYieAmzLcZ3sQ=,tag:N6Rhiwpi4/Wpu7EZ782umA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: discord-bot-update-webhook-token
stringData:
    token: ENC[AES256_GCM,data:rsLXucLWnAQmFohxqQgRwa6Nai6OK34r,iv:d0kwvICT4F0bxXcCsyR/pTmsRQ6jCZt2QxQC6jQBjxQ=,tag:CeUh3tFz816wyCjMA5dUxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UG54VHMrUVErT2xtbDhL
            REpQUjA1L0Y3NUxMUGkra3FsUU8vT01zTVhnClBpNUZnbTZHT0JsNjdsQk1hdkV1
            dVpsVFR0K2tFUHB0enEvL0ZMN2tVWnMKLS0tIDNjL1U4Q2FMM0tVdUYvcWFsOS9M
            RFFmMmZablMwVlRIZlBnZjRqT2J4YzAKoI74oaggQaYm5ut79PZuWwU6qjxSN/Ku
            qoeS3BxEeuVouzLKDIQ4pkABsjVqnJO58A1FTO5gbucrZqNhhCsz0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nmyhrpnparuwdkny03zxc52gn488qumxw865ss3vavkqxvauhfwq0e7y34
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T21:23:24Z"
    mac: ENC[AES256_GCM,data:P06bjQlBG/xgGGqwQpplGc3qlZORUtx4xe1XAMmBecf8Xxb2zzvjAfA0G/pqQjf64/2Q5jM+Qoi3B5GlX2Z3rDG7wBi2tGzWj3yxZMf+YMkRrH+ifoOMFzbRBhosq+aphaBDXdAXowiVQGr2xkPOcig6X37U19q4gVU+LCi9uGs=,iv:7cfrUeD78VuMtbvUDsbtmGytuYdHtRsYieAmzLcZ3sQ=,tag:N6Rhiwpi4/Wpu7EZ782umA==,type:str]
    version: 3.13.3
