{
 "title": "Geometa - main",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "query", "label": "Search Query" },
   { "name": "level", "query": "info, error" }
  ]
 },
 "panels": [
  {
   "title": "Healthy Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_ready{namespace=`geometa-prod`, condition=`true`} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request time",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "h": 8, "w": 24 },
   "targets": [
    {
     "expr": "quantile_over_time(\n  0.50,\n  {namespace=\"geometa-prod\",app=\"frontend\"} != \"Listening on\"\n    | json\n    | __error__ = \"\"\n    | path = \"/maps\"\n    | unwrap rt[$__interval]\n)\nby ()",
     "direction": "backward",
     "legendFormat": "0.50"
    },
    {
     "expr": "quantile_over_time(\n  0.75,\n  {namespace=\"geometa-prod\",app=\"frontend\"} != \"Listening on\"\n    | json\n    | __error__ = \"\"\n    | path = \"/maps\"\n    | unwrap rt[$__interval]\n)\nby ()",
     "direction": "backward",
     "legendFormat": "0.75"
    },
    {
     "expr": "quantile_over_time(\n  0.95,\n  {namespace=\"geometa-prod\",app=\"frontend\"} != \"Listening on\"\n    | json\n    | __error__ = \"\"\n    | path = \"/maps\"\n    | unwrap rt[$__interval]\n)\nby ()",
     "direction": "backward",
     "legendFormat": "0.95"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=`geometa-prod`, app=~`frontend|api`} != `Listening on ` |= `${query:regex}` | json | level =~ `$level`"
    }
   ]
  }
 ]
}