apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: hcloud
  namespace: kube-system
spec:
  interval: 24h
  url: https://charts.hetzner.cloud
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hcloud-cloud-controller-manager
  namespace: kube-system
spec:
  releaseName: hcloud-cloud-controller-manager
  chart:
    spec:
      chart: hcloud-cloud-controller-manager
      version: 1.24.0
      sourceRef:
        kind: HelmRepository
        name: hcloud
        namespace: kube-system
  interval: 1h0m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hcloud-csi
  namespace: kube-system
spec:
  releaseName: hcloud-csi
  chart:
    spec:
      chart: hcloud-csi
      version: 2.13.0
      sourceRef:
        kind: HelmRepository
        name: hcloud
        namespace: kube-system
  interval: 1h0m0s
