apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: hcloud
    namespace: kube-system
stringData:
    token: ENC[AES256_GCM,data:nee/ivJaJ/RAYWFczeayOx7xHI7S2wbH77Oz0TbS15mPE3jc1hmhoVfuRm+TEVFvA0i4HpMEfB6LzDSoSBfrug==,iv:apB+c5NFnLa5Id+Zvw8ofam45WshD7gZtltwRrqXA2I=,tag:EMEqW+uPBXAxv1STi6u7Pg==,type:str]
sops:
    age:
        - recipient: age1nmyhrpnparuwdkny03zxc52gn488qumxw865ss3vavkqxvauhfwq0e7y34
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMElVRGtScS82N1I5RjR5
            eG9wWEd1bVRGdS9Ha3JTTnhIS3U5cUgvS0ZRCkVsNFFpd3o1NlJWWU0zSzJjdWpn
            MFNvOVVYL0tabWxSNnRlMHhiUDJhdFUKLS0tIG5mcUZ0Z0hvNndvVnlwR00wZDdZ
            RkowOEdyYjkxZktxdjcwVXFMUEprY0kKMvULF2A/IEvrF674/7wF7Gai8jFDpPkp
            Nnq5Kf9UJJdJ/UR7eMu7niqoDFY0jc0cqthKNk2cH4UqXemy8g1EZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-06T22:32:28Z"
    mac: ENC[AES256_GCM,data:tFVs4VQqcX53JzrshxOhOt0S0iLUrLxOrZtKuMRyZGoh4psZhgrkD2oFhCl+0uyiWP8lnZK2ByEJopf7eF0ZaqbRO9X+GMUkxfyAsi4DzV4e/Mz49Ygj1iIZJcjMZxjXq7A/wJ7nGtDDVj2xmU1yAPP6wcJyUz+Gd6X/b+oqWwo=,iv:nOpJHNb4g5OTmiaMX2l28mSonOE2Jj141lp0Bm+WpvA=,tag:UUKPmbj15D7Gmyf5qELpFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
