apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 24h
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  releaseName: tailscale-operator
  chart:
    spec:
      chart: tailscale-operator
      version: 1.86.2
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
  interval: 1h0m0s
  valuesFrom:
    - kind: Secret
      name: tailscale
