apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEJTCCAo2gAwIBAgIURkDW1x8CBpr4bCRtaRzNX5rXfHUwDQYJKoZIhvcNAQEL
    BQAwGjEYMBYGA1UEAwwPZ2VvbWV0YS1uYXRzLWNhMB4XDTI2MDkyNDEzMDYyNVoX
    DTM2MDkyMTEzMDYyNVowGjEYMBYGA1UEAwwPZ2VvbWV0YS1uYXRzLWNhMIIBojAN
    BgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAuEzd5Zhq7fo5zAaKqJ6pl2c64tk7
    Df4PYxcfm4x9AcDsVGA6/b05KMAzeh1hzVDknxaoeHyeqiogtFEd+ntO/hptSJbs
    Wv5OHAxqXZYeaoKNnbnMKY8SFG70uairBrrxIsCTLiTVvuxngC0dYuIExntUnIY6
    t29XXphjaqEsrGdgJC1+UqU4pQ04wPvMz3c7xZGpuK8e2tUzgSWpJfSRr3sS4CLt
    xyN3yP8kmstjYgZQd6BfNZCo347Ux+kh2lyP/5Xwl676R14OLHkPxjs0KgS9jDmz
    yw7MIRY3sJAUE9gnMLzvswJFeATXWyTSyOTSjmU1XgRv5Bt3ws/e34we/e8tdyry
    Cr439qt8mP5jMaEzTfh6QoTSvUt9g5fqdrXtiZOhb8CN2y85eGBpktxy5tsABKPz
    UQrnW1pYC6YkYfRejPraX9+IK3ex3bFwnYUMnF+H4lObkI30kB6Q7/TydiHXyprO
    xaUtQ/Tb4VGCXj75Ufbg+EskQ1B0Gg2rVGunAgMBAAGjYzBhMB0GA1UdDgQWBBQs
    WvTy1bsHy7OKPJbD4pDdj5smtzAfBgNVHSMEGDAWgBQsWvTy1bsHy7OKPJbD4pDd
    j5smtzAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjANBgkqhkiG9w0B
    AQsFAAOCAYEAb18RvQb6p793AJABsG4SwrbwyRpRalnSQH9AvucDgQl6Nqz6Fwts
    aQB0KoQToKrZc+pNwZogunuKbU3p/KS4ECHgDDwWzD9NGajqVQoXGPSK6nSDX8vS
    QixgZc5d0FbTQaIb8EyFra5Zw6KsmoR4k3pqqAgF3q/YufGO2mLIDXZ7sLhaC9wi
    GGJEeg1yR/Myz7/BlXeWlw+t7I2rfmgF5Kuv6c7R6sY9GlzW/ROpQ4iMd0TzgJ6e
    sJqRSgHg73P+W7WI/j7B/r6K/5xdEeD78CX0xPk//peMI822KWf0v9VqtgcYbE9Z
    45e6iSk82w4xyXtd6Ib86w9TIW+pTrw/aqK9rPbkFZj8/kBe6SNHu/+qeWiDST+y
    bJKOFd8PON56yT842EvuF9q5JTRtTGbhGohmo1Rwe7WVJg7ryFwD+0zFX4tSp+JX
    eBc84V80QhdjrEObjdzQ3FWKe+mjgnvP1nswnNisTVvy1YPSjmkGKsYlBZQ+rtXP
    8BvPyPDHZIpW
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: nats-ca
