apiVersion: v1
kind: Secret
metadata:
    name: api
stringData:
    #ENC[AES256_GCM,data:Cvjy2MOcibja,iv:xoqY5GyhZVWfFXWYhMT72ZbwWQ7rj8B+e3YXL2XrnCE=,tag:HGaXgRRE+Vh3Av7Z5Ujfeg==,type:comment]
    FRONTEND_API_TOKEN: ENC[AES256_GCM,data:honlT1pcIm4sb5auVBqNaTdD3KDe/G7Pm+mYQ7KDZQKrHxQxwKSraYMu3GAZJJ6mbSsalUbcyW7zf+Oz++I4Yw==,iv:NhBuMY9984PF46aiHgsahqJr6aWyXJvWdtqQ18kCrV0=,tag:9D3NUToCm4cb767N4/HHfQ==,type:str]
    #ENC[AES256_GCM,data:t6QpiCUZ+SxuXc/ESe0=,iv:QBrVp/+YsKncBLVuEvyzZmzuKJqN4Yr0HZ5KLMNINWg=,tag:qnAXuRhRJUYLGAVVkCj/Ww==,type:comment]
    IMAGES_S3_URL: ENC[AES256_GCM,data:WN6ukNvS5Zl3eCGQCMTGewxnEG4LWjZp3isu88moWEpx2WF+TuwuHdP9HNQtlpEHjILhglj7GTUAOp9I9qiJLLa6Iw==,iv:/PntlF8TSwBUDS3jUtq3Z8tZlQKcMUJwwNGfivxfrhA=,tag:hcxa8EqnswGaWQUkuHdziw==,type:str]
    IMAGES_S3_ACCESS_KEY: ENC[AES256_GCM,data:x2mq2aiqfs5trk0TPPuhWic58u5ZoFqBwmEgRqmPT8E=,iv:bTHF6Q0aio9gTM5viHUA+DX/6UlQofOuIZxoAkotIno=,tag:JnlW/D9uCUAnUIrwlxJNqw==,type:str]
    IMAGES_S3_SECRET_KEY: ENC[AES256_GCM,data:/UZY47suRYCSaEKg0DJpZRDL+XelDFdMvhXbhxS9Oi7Ni8RsZa2cXexvTP/TVM5U83eW6recN6PMcXR4N5X7SA==,iv:qyqKbCLc8cYU86xN9OYrvNpA89JbdIGYNwU0Z4mwUUI=,tag:b0BnUVokQPjDtjNu7SofBA==,type:str]
    #ENC[AES256_GCM,data:VqNnVjK7,iv:zOAFWP7/jgvHj2OJelSBIOVSDoOugiJ6glgkIBcAlmU=,tag:CyL+r6snc+zUE2sybC5NAA==,type:comment]
    CRONJOBS_API_TOKEN: ENC[AES256_GCM,data:vdYPNMU/+L5tzYdALZhZ5S++A/9sy53Y,iv:QKMLpbGNc8f/QSDvncUDX3wvr23uNlpSfoOSgNZU7hI=,tag:mmfiSPSjhsgz81odaxyS9g==,type:str]
    NFCA_TOKEN: ENC[AES256_GCM,data:vnllFg5dej7tYqNbpNvu/Tsb9BuHaY31pCWGXf5OmeIm+PX/z+0EqhfhVdqExB5Baz5jel8M1rtrnaRk2ZZjHJdKV60pVVymwKqh2ARIhVS67hlK4DBaRjPFAkQCfVKsVq/PcxIGj6OvWfye/BajPn3Tamnrbge51q3YT8y3O3E9tbpx+3JSKSqVR3Djh+IqBRRx2x9ATr/ECoWADW8pLIpF,iv:CHj+gFI8Y/5raxC/u5mgYDZltFP78gfKd+KuMH8uJQE=,tag:Dx22r6xhs2iwVTpi/+4cZw==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:mZZkGJcRFKQxISOYUbP/H4eVtCW0Xwu5mtnROcJcM5E6xG9UcK/Pqe0rePjDHDAOTjSeiKsMKFtZnlgBQ7pQRv5lYRvMmFKWpjPSn06oB27vbu2FYtbzikDo1OQVKBg=,iv:yhXf0LeboZSPxEWtSXif5P2EaxIBuRkaXZZa6jxhNTY=,tag:x7va6N/7QE6fgju8/ohk1Q==,type:str]
    GOOGLE_MAPS_API_KEY: ENC[AES256_GCM,data:O8T3E+/ralRAexTGZmKDD1mcIodbsrsOpvdiAdXG5H4LUfnobTlk,iv:4rC3ZgMFdm9K6AreMbEl5Z11+jWgjAK53eU/YxKKX7g=,tag:DcD/BKgjT8GO2p7PHywB0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UG54VHMrUVErT2xtbDhL
            REpQUjA1L0Y3NUxMUGkra3FsUU8vT01zTVhnClBpNUZnbTZHT0JsNjdsQk1hdkV1
            dVpsVFR0K2tFUHB0enEvL0ZMN2tVWnMKLS0tIDNjL1U4Q2FMM0tVdUYvcWFsOS9M
            RFFmMmZablMwVlRIZlBnZjRqT2J4YzAKoI74oaggQaYm5ut79PZuWwU6qjxSN/Ku
            qoeS3BxEeuVouzLKDIQ4pkABsjVqnJO58A1FTO5gbucrZqNhhCsz0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nmyhrpnparuwdkny03zxc52gn488qumxw865ss3vavkqxvauhfwq0e7y34
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T18:36:01Z"
    mac: ENC[AES256_GCM,data:31uxLvY5tbKbpb6GB5eOCYzQ+D16pMVdPhDK6C5Z5SX/B00ZU5PsUPreR8OcyPX92AmvSZaywNSetaNqkpqL3wcxnt9ryHK1b4O2YkcJNVma9u2EUqhzyOZcOC6wS1TZyyNKr90B5tEXIyfVTng6gio/CxiRQzbR9L/loNqvEp8=,iv:mETaLYEbArPBbMkpVJ+/LqCsednQBymNMV42WKxF2fQ=,tag:F7JHh+Dv8ac4IGMv2yfxbQ==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: api-update-webhook-token
stringData:
    token: ENC[AES256_GCM,data:FNH1wCTuAOSfGcUJAacS56EcWiFgPH9C,iv:OnLSN4ebcty18q6nuEDP9xtyUiS2Vto6p2ui7cgiUyw=,tag:4usLF99o+0QM4qy9MbIklA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UG54VHMrUVErT2xtbDhL
            REpQUjA1L0Y3NUxMUGkra3FsUU8vT01zTVhnClBpNUZnbTZHT0JsNjdsQk1hdkV1
            dVpsVFR0K2tFUHB0enEvL0ZMN2tVWnMKLS0tIDNjL1U4Q2FMM0tVdUYvcWFsOS9M
            RFFmMmZablMwVlRIZlBnZjRqT2J4YzAKoI74oaggQaYm5ut79PZuWwU6qjxSN/Ku
            qoeS3BxEeuVouzLKDIQ4pkABsjVqnJO58A1FTO5gbucrZqNhhCsz0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nmyhrpnparuwdkny03zxc52gn488qumxw865ss3vavkqxvauhfwq0e7y34
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T18:36:01Z"
    mac: ENC[AES256_GCM,data:31uxLvY5tbKbpb6GB5eOCYzQ+D16pMVdPhDK6C5Z5SX/B00ZU5PsUPreR8OcyPX92AmvSZaywNSetaNqkpqL3wcxnt9ryHK1b4O2YkcJNVma9u2EUqhzyOZcOC6wS1TZyyNKr90B5tEXIyfVTng6gio/CxiRQzbR9L/loNqvEp8=,iv:mETaLYEbArPBbMkpVJ+/LqCsednQBymNMV42WKxF2fQ=,tag:F7JHh+Dv8ac4IGMv2yfxbQ==,type:str]
    version: 3.13.2
