apiVersion: v1
kind: Secret
metadata:
    name: api
stringData:
    #ENC[AES256_GCM,data:Cvjy2MOcibja,iv:xoqY5GyhZVWfFXWYhMT72ZbwWQ7rj8B+e3YXL2XrnCE=,tag:HGaXgRRE+Vh3Av7Z5Ujfeg==,type:comment]
    FRONTEND_API_TOKEN: ENC[AES256_GCM,data:honlT1pcIm4sb5auVBqNaTdD3KDe/G7Pm+mYQ7KDZQKrHxQxwKSraYMu3GAZJJ6mbSsalUbcyW7zf+Oz++I4Yw==,iv:NhBuMY9984PF46aiHgsahqJr6aWyXJvWdtqQ18kCrV0=,tag:9D3NUToCm4cb767N4/HHfQ==,type:str]
    #ENC[AES256_GCM,data:t6QpiCUZ+SxuXc/ESe0=,iv:QBrVp/+YsKncBLVuEvyzZmzuKJqN4Yr0HZ5KLMNINWg=,tag:qnAXuRhRJUYLGAVVkCj/Ww==,type:comment]
    IMAGES_S3_URL: ENC[AES256_GCM,data:tJ28P7r/6AvQDMKyQgrkT198bzXd6VnI4njf4T1/cgnzoDjMhVRjwVu2vyHY68HZiCQ=,iv:X/v/xKP/hlonaec2bt7SbrIyM9j/CKYNC/ymzvU521s=,tag:kGQKI0834u8rVFMNre75Uw==,type:str]
    IMAGES_S3_ACCESS_KEY: ENC[AES256_GCM,data:1ZqLJEuZxds8F4MeKKfmRprWZ1E=,iv:fE+XQdP/n7F1buV17bhTTRo9ghrI5nO/EgCtWWjOOxw=,tag:pdyoGbhb7gu00dkJMslKpw==,type:str]
    IMAGES_S3_SECRET_KEY: ENC[AES256_GCM,data:f0s7WRFscUbcaYnV/a1fxgR+P1nMGI2J3hAL+bR2IW0HC45APb7nbg==,iv:3QZR+WKiZhwTjzLI/ZTNyEBb5tSW4cviaZ/TlwP4Sxw=,tag:EYgJ4Pdi0u1Ihtb5OkKm5w==,type:str]
    #ENC[AES256_GCM,data:VqNnVjK7,iv:zOAFWP7/jgvHj2OJelSBIOVSDoOugiJ6glgkIBcAlmU=,tag:CyL+r6snc+zUE2sybC5NAA==,type:comment]
    CRONJOBS_API_TOKEN: ENC[AES256_GCM,data:vdYPNMU/+L5tzYdALZhZ5S++A/9sy53Y,iv:QKMLpbGNc8f/QSDvncUDX3wvr23uNlpSfoOSgNZU7hI=,tag:mmfiSPSjhsgz81odaxyS9g==,type:str]
    NFCA_TOKEN: ENC[AES256_GCM,data:vnllFg5dej7tYqNbpNvu/Tsb9BuHaY31pCWGXf5OmeIm+PX/z+0EqhfhVdqExB5Baz5jel8M1rtrnaRk2ZZjHJdKV60pVVymwKqh2ARIhVS67hlK4DBaRjPFAkQCfVKsVq/PcxIGj6OvWfye/BajPn3Tamnrbge51q3YT8y3O3E9tbpx+3JSKSqVR3Djh+IqBRRx2x9ATr/ECoWADW8pLIpF,iv:CHj+gFI8Y/5raxC/u5mgYDZltFP78gfKd+KuMH8uJQE=,tag:Dx22r6xhs2iwVTpi/+4cZw==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:mZZkGJcRFKQxISOYUbP/H4eVtCW0Xwu5mtnROcJcM5E6xG9UcK/Pqe0rePjDHDAOTjSeiKsMKFtZnlgBQ7pQRv5lYRvMmFKWpjPSn06oB27vbu2FYtbzikDo1OQVKBg=,iv:yhXf0LeboZSPxEWtSXif5P2EaxIBuRkaXZZa6jxhNTY=,tag:x7va6N/7QE6fgju8/ohk1Q==,type:str]
    GOOGLE_MAPS_API_KEY: ENC[AES256_GCM,data:O8T3E+/ralRAexTGZmKDD1mcIodbsrsOpvdiAdXG5H4LUfnobTlk,iv:4rC3ZgMFdm9K6AreMbEl5Z11+jWgjAK53eU/YxKKX7g=,tag:DcD/BKgjT8GO2p7PHywB0A==,type:str]
sops:
    age:
        - recipient: age1nmyhrpnparuwdkny03zxc52gn488qumxw865ss3vavkqxvauhfwq0e7y34
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UG54VHMrUVErT2xtbDhL
            REpQUjA1L0Y3NUxMUGkra3FsUU8vT01zTVhnClBpNUZnbTZHT0JsNjdsQk1hdkV1
            dVpsVFR0K2tFUHB0enEvL0ZMN2tVWnMKLS0tIDNjL1U4Q2FMM0tVdUYvcWFsOS9M
            RFFmMmZablMwVlRIZlBnZjRqT2J4YzAKoI74oaggQaYm5ut79PZuWwU6qjxSN/Ku
            qoeS3BxEeuVouzLKDIQ4pkABsjVqnJO58A1FTO5gbucrZqNhhCsz0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T22:19:30Z"
    mac: ENC[AES256_GCM,data:LoYE8mAW0f0s1w+13tnBZkySlyhdJ27RdGajjvEa3A/jb0wZ8gqFbaiffO2UWRhe5tq44lk7CHu35hxfDCejJl2K/hA9s0cgKNldXZbBfs/5DPGDNMPmE2q5Y/mRwTkj4SLUcKib2nvsBoks6ChOKnvXyeI/3r9T2DD12beq+dA=,iv:y+gBWeYuZvuCFzy4/Bmtsynmww8Rvy7xn4ZQGHR1pLY=,tag:YkRxV36vy2rdTxVoEX932Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: api-update-webhook-token
stringData:
    token: ENC[AES256_GCM,data:FNH1wCTuAOSfGcUJAacS56EcWiFgPH9C,iv:OnLSN4ebcty18q6nuEDP9xtyUiS2Vto6p2ui7cgiUyw=,tag:4usLF99o+0QM4qy9MbIklA==,type:str]
sops:
    age:
        - recipient: age1nmyhrpnparuwdkny03zxc52gn488qumxw865ss3vavkqxvauhfwq0e7y34
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UG54VHMrUVErT2xtbDhL
            REpQUjA1L0Y3NUxMUGkra3FsUU8vT01zTVhnClBpNUZnbTZHT0JsNjdsQk1hdkV1
            dVpsVFR0K2tFUHB0enEvL0ZMN2tVWnMKLS0tIDNjL1U4Q2FMM0tVdUYvcWFsOS9M
            RFFmMmZablMwVlRIZlBnZjRqT2J4YzAKoI74oaggQaYm5ut79PZuWwU6qjxSN/Ku
            qoeS3BxEeuVouzLKDIQ4pkABsjVqnJO58A1FTO5gbucrZqNhhCsz0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T22:19:30Z"
    mac: ENC[AES256_GCM,data:LoYE8mAW0f0s1w+13tnBZkySlyhdJ27RdGajjvEa3A/jb0wZ8gqFbaiffO2UWRhe5tq44lk7CHu35hxfDCejJl2K/hA9s0cgKNldXZbBfs/5DPGDNMPmE2q5Y/mRwTkj4SLUcKib2nvsBoks6ChOKnvXyeI/3r9T2DD12beq+dA=,iv:y+gBWeYuZvuCFzy4/Bmtsynmww8Rvy7xn4ZQGHR1pLY=,tag:YkRxV36vy2rdTxVoEX932Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
