drizzle-generate:
  bunx drizzle-kit generate

drizzle-migrate:
  bunx drizzle-kit migrate

database := "geometa"
db-psql:
  psql -h localhost -U postgres {{database}}

alias db-shell := db-psql

pgcli:
  uvx pgcli postgresql://postgres:postgres@localhost:${TILT_PORT_POSTGRES:-5432}/geometa

pgcli-prod:
  uvx pgcli $PROD_POSTRGRES_URL

environment := "local"
db-dump:
  ./utils/db/backup.sh {{environment}}

db-reset:
  psql -h localhost -U postgres postgres -f utils/db/reset.sql

db-init:
  psql -h localhost -U postgres geometa -f utils/db/init.sql

build TAG:
  buildah bud --platform linux/arm64 -t {{TAG}}
