drizzle-generate:
  bunx drizzle-kit generate

drizzle-migrate:
  bunx drizzle-kit migrate

db-psql:
  psql "{{ env_var_or_default('DATABASE_URL', 'postgresql://postgres:postgres@localhost:5432/geometa') }}"

alias db-shell := db-psql

environment := "local"
db-dump:
  ./utils/db/backup.sh {{environment}}

db-reset:
  psql "{{ env_var_or_default('DATABASE_URL_POSTGRES_DB', 'postgresql://postgres:postgres@localhost:5432/postgres') }}" -f utils/db/reset.sql

db-init:
  psql "{{ env_var_or_default('DATABASE_URL', 'postgresql://postgres:postgres@localhost:5432/geometa') }}" -f utils/db/init.sql

build TAG:
  buildah bud --platform linux/arm64 -t {{TAG}}
